#!/bin/bash

# gem install macgap
macgap build JetChat
cp application.icns JetChat.app/Contents/Resources/

# git clone https://github.com/andreyvit/create-dmg.git
# export PATH="~/create-dmg:$PATH"

create-dmg \
--volname "JetChat" \
--volicon application.icns \
--window-pos 200 120 \
--window-size 600 300 \
--icon-size 100 \
--icon Application.app 200 190 \
--hide-extension Application.app \
--app-drop-link 600 185 \
JetChat.dmg \
JetChat.app